---
##### SET UP APPLICATION #####

# Clone application code
# Is currently hosted from a public GitHub repo
- name: clone git repo
  git:
    repo: 'git@github.com:srikantharun/terraform-packer.git'
    dest: '/srv/app/example-node-app'
    key_file: /root/.ssh/id_ed25519
    accept_hostkey: yes
    force: yes
  become: yes

# Install npm modules
- name: install npm modules
  npm:
    path: /srv/app/example-node-app
    state: present
  become: yes
  become_user: deploy

