---
##### SET UP APPLICATION #####

# Clone application code
# Is currently hosted from a public GitHub repo
- name: clone git repo
  git:
    repo: 'https://github.com/jnordberg/webapp.git'
    dest: '/srv/app/example-node-app'
    clone: yes
    update: yes

# Install npm modules
- name: install npm modules
  npm:
    path: /srv/app/example-node-app
    state: present
